FROM buildpack-deps:jessie

# gpg keys listed at https://github.com/nodejs/node
RUN set -ex \
  && for key in \
    9554F04D7259F04124DE6B476D5A82AC7E37093B \
    94AE36675C464D64BAFA68DD7434390BDBE9B9C5 \
    0034A06D9D9B0064CE8ADF6BF1747F4AD2306D93 \
    FD3A5288F042B6850C66B31F09FE44734EB7990E \
    71DCFD284A79C3B38668286BC97EC7A07EDE3FC1 \
    DD8F2338BAE7501E3DD5AC78C273792F7D83545D \
    B9AE9905FFD7803F25714661B63B535A4C206CA9 \
    C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8 \
  ; do \
    gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
  done

ENV NPM_CONFIG_LOGLEVEL info
ENV NODE_VERSION 4.6.0

RUN curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.xz" \
  && curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt.asc" \
  && gpg --batch --decrypt --output SHASUMS256.txt SHASUMS256.txt.asc \
  && grep " node-v$NODE_VERSION-linux-x64.tar.xz\$" SHASUMS256.txt | sha256sum -c - \
  && tar -xJf "node-v$NODE_VERSION-linux-x64.tar.xz" -C /usr/local --strip-components=1 \
  && rm "node-v$NODE_VERSION-linux-x64.tar.xz" SHASUMS256.txt.asc SHASUMS256.txt \
  && ln -s /usr/local/bin/node /usr/local/bin/nodejs

# RUN npm install -g cnpm --registry=https://registry.npm.taobao.org
RUN npm install -g nrm  \
  &&  nrm use npm
# RUN apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3 \
#   &&  echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
#   &&  apt-get update \
#   &&  apt-get install yarn

RUN npm install -g express \
    &&  npm install -g url \
    &&  npm install -g superagent  \
    &&  npm install -g cheerio \
    &&  npm install -g eventproxy \
    &&  npm install -g webpack \
    &&  npm install -g react \
    &&  npm install -g react-dom  \
    &&  npm install -g express  \
    &&  npm install -g grunt-cli    \
    &&  npm install -g yo    \
    &&  npm install -g bower    \
    &&  npm install -g vue@2.0.5    \
    &&  npm install -g vue-template-compiler@2.0.5    \
    &&  npm install -g gulp    \
    &&  npm install -g vue-cli    \
    &&  npm install -g vuetable  \
    &&  npm install -g vue-resource  \
    &&  npm install -g vue-router  \
    &&  npm install -g vue-tables  \
    &&  npm install -g vue-lazyload \
    &&  npm install -g vue-validator  \
    &&  npm install -g react-native-cli \
    &&  npm install -g electron-prebuilt \
    &&  npm install -g scrat \
    &&  npm install -g cross-env \
    &&  npm install -g koa \
    &&  npm install -g iview \
    &&  npm install -g vue-strap
    # &&  npm install -g N3-components

# RUN npm install -g grunt-cli    &&  \
#     npm install

CMD [ "node" ]
